import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const todoApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: 'https://6610811b0640280f219d177f.mockapi.io' }),
  reducerPath: 'todos',
  // Tag types are used for caching and invalidation.
  tagTypes: ['Todos'],
  endpoints: (builder) => ({
    // Supply generics for the return type (in this case `TodoItem[]`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getTodos: builder.query<TodoItem[], void>({
      query: () => '/todos',
      // transformResponse: (response: GetTodosApiResponse) => response.todos,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result) => (result ? result.map(({ id }) => ({ type: 'Todos', id })) : []),
    }),
    addTodo: builder.mutation<void, TodoItem>({
      query: (newTodo) => ({
        url: '/todos',
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: newTodo,
      }),
      invalidatesTags: ['Todos'],
    }),
    updateTodo: builder.mutation<TodoItem, TodoItem>({
      query: (updatedTodo) => ({
        url: `/todos/${updatedTodo.id}`,
        method: 'PUT',
        body: updatedTodo,
      }),
      invalidatesTags: ['Todos'],
    }),
    deleteTodo: builder.mutation<TodoItem, TodoItem['id']>({
      query: (id) => ({
        url: `/todos/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Todos'],
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
export const {
  useGetTodosQuery,
  useAddTodoMutation,
  useDeleteTodoMutation,
  useUpdateTodoMutation,
} = todoApiSlice;
